using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ArticleWorkflow
{
    public class Article : ArticleComponent
    {
        public ArticleState articleState;

        public Article()
        {

        }
            
        public override void Operation()
        {
            throw new System.NotImplementedException();
        }
    }
}

/*
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMCC.Models
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Article : ArticleWorkflow.ArticleComponent
    {
        public ArticleWorkflow.ArticleState articleState;


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Reviews = new HashSet<Review>();
        }

        public override void Operation()
        {
            throw new System.NotImplementedException();
        }

        public int ArticleId { get; set; }
        public string ArticleUserId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ArticleState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}

*/
