//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMCCTests.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Publishes = new HashSet<Publish>();
        }
    
        public int ArticleId { get; set; }
        public string ArticleUserId { get; set; }
        public Nullable<int> ArticleReviewId { get; set; }
        [Required(ErrorMessage = "This field may not be empty", AllowEmptyStrings = false)]
        public string Title { get; set; }
        [Required(ErrorMessage = "This field may not be empty", AllowEmptyStrings = false)]
        public string Text { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public int ArticleStateId { get; set; }
    
        public virtual ArticleState ArticleState { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Review Review { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publish> Publishes { get; set; }
    }
}
