//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMCCTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publish
    {
        public int PublishId { get; set; }
        public int ArticleId { get; set; }
        public System.DateTime PublishDate { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
